// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: proto/courier/v1/courier.proto

package courierv1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_CREATED     OrderStatus = 1
	OrderStatus_ORDER_STATUS_ASSIGNED    OrderStatus = 2
	OrderStatus_ORDER_STATUS_IN_TRANSIT  OrderStatus = 3
	OrderStatus_ORDER_STATUS_DELIVERED   OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELED    OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_CREATED",
		2: "ORDER_STATUS_ASSIGNED",
		3: "ORDER_STATUS_IN_TRANSIT",
		4: "ORDER_STATUS_DELIVERED",
		5: "ORDER_STATUS_CANCELED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_CREATED":     1,
		"ORDER_STATUS_ASSIGNED":    2,
		"ORDER_STATUS_IN_TRANSIT":  3,
		"ORDER_STATUS_DELIVERED":   4,
		"ORDER_STATUS_CANCELED":    5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_courier_v1_courier_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_courier_v1_courier_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_courier_v1_courier_proto_rawDescGZIP(), []int{0}
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SellerAddress   string                 `protobuf:"bytes,1,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,2,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	WeightGrams     int32                  `protobuf:"varint,3,opt,name=weight_grams,json=weightGrams,proto3" json:"weight_grams,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_courier_v1_courier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_v1_courier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_courier_v1_courier_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetWeightGrams() int32 {
	if x != nil {
		return x.WeightGrams
	}
	return 0
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status          OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=courier.v1.OrderStatus" json:"status,omitempty"`
	SellerAddress   string                 `protobuf:"bytes,3,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,4,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	WeightGrams     int32                  `protobuf:"varint,5,opt,name=weight_grams,json=weightGrams,proto3" json:"weight_grams,omitempty"`
	CreatedAt       *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_courier_v1_courier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_v1_courier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_courier_v1_courier_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *Order) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *Order) GetWeightGrams() int32 {
	if x != nil {
		return x.WeightGrams
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_courier_v1_courier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_v1_courier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_courier_v1_courier_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TrackOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackOrderRequest) Reset() {
	*x = TrackOrderRequest{}
	mi := &file_proto_courier_v1_courier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackOrderRequest) ProtoMessage() {}

func (x *TrackOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_v1_courier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackOrderRequest.ProtoReflect.Descriptor instead.
func (*TrackOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_courier_v1_courier_proto_rawDescGZIP(), []int{3}
}

func (x *TrackOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStatus     OrderStatus            `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=courier.v1.OrderStatus" json:"new_status,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_proto_courier_v1_courier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_v1_courier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_proto_courier_v1_courier_proto_rawDescGZIP(), []int{4}
}

func (x *OrderEvent) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderEvent) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_courier_v1_courier_proto protoreflect.FileDescriptor

const file_proto_courier_v1_courier_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/courier/v1/courier.proto\x12\n" +
	"courier.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\x12CreateOrderRequest\x12%\n" +
	"\x0eseller_address\x18\x01 \x01(\tR\rsellerAddress\x12)\n" +
	"\x10receiver_address\x18\x02 \x01(\tR\x0freceiverAddress\x12!\n" +
	"\fweight_grams\x18\x03 \x01(\x05R\vweightGrams\"\xf8\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.courier.v1.OrderStatusR\x06status\x12%\n" +
	"\x0eseller_address\x18\x03 \x01(\tR\rsellerAddress\x12)\n" +
	"\x10receiver_address\x18\x04 \x01(\tR\x0freceiverAddress\x12!\n" +
	"\fweight_grams\x18\x05 \x01(\x05R\vweightGrams\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"#\n" +
	"\x11TrackOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x7f\n" +
	"\n" +
	"OrderEvent\x126\n" +
	"\n" +
	"new_status\x18\x01 \x01(\x0e2\x17.courier.v1.OrderStatusR\tnewStatus\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\xb4\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_CREATED\x10\x01\x12\x19\n" +
	"\x15ORDER_STATUS_ASSIGNED\x10\x02\x12\x1b\n" +
	"\x17ORDER_STATUS_IN_TRANSIT\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x04\x12\x19\n" +
	"\x15ORDER_STATUS_CANCELED\x10\x052\xd5\x01\n" +
	"\x0eCourierService\x12@\n" +
	"\vCreateOrder\x12\x1e.courier.v1.CreateOrderRequest\x1a\x11.courier.v1.Order\x12:\n" +
	"\bGetOrder\x12\x1b.courier.v1.GetOrderRequest\x1a\x11.courier.v1.Order\x12E\n" +
	"\n" +
	"TrackOrder\x12\x1d.courier.v1.TrackOrderRequest\x1a\x16.courier.v1.OrderEvent0\x01B9Z7github.com/moondoggy/courier/proto/courier/v1;courierv1b\x06proto3"

var (
	file_proto_courier_v1_courier_proto_rawDescOnce sync.Once
	file_proto_courier_v1_courier_proto_rawDescData []byte
)

func file_proto_courier_v1_courier_proto_rawDescGZIP() []byte {
	file_proto_courier_v1_courier_proto_rawDescOnce.Do(func() {
		file_proto_courier_v1_courier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_courier_v1_courier_proto_rawDesc), len(file_proto_courier_v1_courier_proto_rawDesc)))
	})
	return file_proto_courier_v1_courier_proto_rawDescData
}

var file_proto_courier_v1_courier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_courier_v1_courier_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_courier_v1_courier_proto_goTypes = []any{
	(OrderStatus)(0),            // 0: courier.v1.OrderStatus
	(*CreateOrderRequest)(nil),  // 1: courier.v1.CreateOrderRequest
	(*Order)(nil),               // 2: courier.v1.Order
	(*GetOrderRequest)(nil),     // 3: courier.v1.GetOrderRequest
	(*TrackOrderRequest)(nil),   // 4: courier.v1.TrackOrderRequest
	(*OrderEvent)(nil),          // 5: courier.v1.OrderEvent
	(*timestamp.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_courier_v1_courier_proto_depIdxs = []int32{
	0, // 0: courier.v1.Order.status:type_name -> courier.v1.OrderStatus
	6, // 1: courier.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: courier.v1.OrderEvent.new_status:type_name -> courier.v1.OrderStatus
	6, // 3: courier.v1.OrderEvent.created_at:type_name -> google.protobuf.Timestamp
	1, // 4: courier.v1.CourierService.CreateOrder:input_type -> courier.v1.CreateOrderRequest
	3, // 5: courier.v1.CourierService.GetOrder:input_type -> courier.v1.GetOrderRequest
	4, // 6: courier.v1.CourierService.TrackOrder:input_type -> courier.v1.TrackOrderRequest
	2, // 7: courier.v1.CourierService.CreateOrder:output_type -> courier.v1.Order
	2, // 8: courier.v1.CourierService.GetOrder:output_type -> courier.v1.Order
	5, // 9: courier.v1.CourierService.TrackOrder:output_type -> courier.v1.OrderEvent
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_courier_v1_courier_proto_init() }
func file_proto_courier_v1_courier_proto_init() {
	if File_proto_courier_v1_courier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_courier_v1_courier_proto_rawDesc), len(file_proto_courier_v1_courier_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_courier_v1_courier_proto_goTypes,
		DependencyIndexes: file_proto_courier_v1_courier_proto_depIdxs,
		EnumInfos:         file_proto_courier_v1_courier_proto_enumTypes,
		MessageInfos:      file_proto_courier_v1_courier_proto_msgTypes,
	}.Build()
	File_proto_courier_v1_courier_proto = out.File
	file_proto_courier_v1_courier_proto_goTypes = nil
	file_proto_courier_v1_courier_proto_depIdxs = nil
}
